# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QAs3QW_GRIrqjyHs1ADv66p6QS_iyCih
"""

token ='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'
username = "Aerie55"
repo ='lecture1'

!git config --global user.name "Aerie55"
!git config --global user.email "julkaczy151@gmail.com"
!git config --global user.password "Python235"

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv('Salary Data.csv')


plt.figure(figsize=(12, 6))
sns.boxplot(data=data, x='Education Level', y='Salary', hue='Gender')

plt.title('Salary Distribution by Education Level and Gender')
plt.xlabel('Education Level')
plt.ylabel('Salary')

plt.xticks(rotation=45)
plt.tight_layout()
plt.show()